install.packages('devtools')
require(devtools)
install_github("slidify", "ramnathv")
install_github("slidifyLibraries", "ramnathv")
library(slidify)
setwd('/home/poemcao/slides')
#author('slides')
slidify("2013-03-04-cuhk.Rmd")
publish(user = "poemcao", repo = "slides")